[custom]

;规则集定义
ruleset=🚨 全球拦截,https://raw.githubusercontent.com/syfirefox/Luci-App-Backup/refs/heads/master/ClashRule/Ban.list
ruleset=📶 Wificalling,https://raw.githubusercontent.com/syfirefox/Luci-App-Backup/refs/heads/master/ClashRule/Wificalling.list
ruleset=🍭 SpecialDirect,https://raw.githubusercontent.com/syfirefox/Luci-App-Backup/refs/heads/master/ClashRule/Special-Direct.list
ruleset=🤖 AI,https://raw.githubusercontent.com/syfirefox/Luci-App-Backup/refs/heads/master/ClashRule/Ai.list
;ruleset=💽 PikPak网盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PikPak/PikPak.list
ruleset=🅱️ 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/qichiyuhub/rule/master/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve

ruleset=💰 Bybit,https://raw.githubusercontent.com/syfirefox/Luci-App-Backup/refs/heads/master/ClashRule/bybit.list
ruleset=💵 Paypal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PayPal/PayPal.list
ruleset=💳 Wise,https://raw.githubusercontent.com/syfirefox/Luci-App-Backup/refs/heads/master/ClashRule/Wise.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list
ruleset=🦄 DisneyPlus,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Disney/Disney.list
ruleset=📺 MAX,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
ruleset=🎞️ HULU,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Hulu/Hulu.list
ruleset=🎶 Tiktok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🎙️ Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list
ruleset=🛞 Discord,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Discord/Discord.list
ruleset=🎬 Youtube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=🌐 Google服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list

;ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🐟 漏网之鱼,[]FINAL

;策略组定义

custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔰 手动切换`select`.*
custom_proxy_group=🚀 节点选择`select`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]♒ ikuuu故转`[]🔰 手动切换`[]DIRECT




custom_proxy_group=😈 自定义节点`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]♒ ikuuu故转`[]🔰 手动切换
custom_proxy_group=⚽ 链式自定义`select`.*`[]♒ ikuuu故转
custom_proxy_group=🧩 链式组件`select`.*`[]♒ ikuuu故转


;custom_proxy_group=🆓 Free节点`select`(?i)^(?!.*(THANK|CDN)).*(免费|日本).*$`http://www.gstatic.com/generate_204`300,,50



custom_proxy_group=🚨 全球拦截`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]😈 自定义节点`[]🔰 手动切换`[]♻️ 自动选择
custom_proxy_group=🍭 SpecialDirect`select`[]DIRECT`[]🚀 节点选择`[]😈 自定义节点`[]⚽ 链式自定义`[]🔰 手动切换`[]♻️ 自动选择
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]☪️ 美国故转`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]😈 自定义节点`[]DIRECT
;custom_proxy_group=💽 PikPak网盘`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🔰 手动切换`[]♻️ 自动选择

custom_proxy_group=💰 Bybit`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]DIRECT
custom_proxy_group=💵 Paypal`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]DIRECT
custom_proxy_group=💳 Wise`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]😈 自定义节点`[]DIRECT
custom_proxy_group=📶 Wificalling`select`[]DIRECT`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]😈 自定义节点`[]⚽ 链式自定义
custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]😈 自定义节点`[]DIRECT
custom_proxy_group=🦄 DisneyPlus`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]😈 自定义节点`[]DIRECT
custom_proxy_group=📺 MAX`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]😈 自定义节点`[]DIRECT
custom_proxy_group=🎞️ HULU`select`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🔰 手动切换`[]😈 自定义节点
custom_proxy_group=🎶 Tiktok`select`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🔯 日本故转`[]♒ ikuuu故转`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]😈 自定义节点`[]⚽ 链式自定义`[]DIRECT
custom_proxy_group=🎙️ Spotify`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]♊ 香港故转`[]🔰 手动切换`[]😈 自定义节点`[]DIRECT
custom_proxy_group=🅱️ 哔哩哔哩`select`[]🇭🇰 香港节点`[]♊ 香港故转`[]DIRECT
custom_proxy_group=🛞 Discord`select`[]🚀 节点选择`[]🇺🇸 美国节点`[]☪️ 美国故转`[]🔰 手动切换`[]😈 自定义节点`[]DIRECT
custom_proxy_group=🎬 Youtube`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]😈 自定义节点`[]⚽ 链式自定义`[]🔰 手动切换`[]DIRECT
custom_proxy_group=🌐 Google服务`select`[]🎬 Youtube`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]😈 自定义节点`[]⚽ 链式自定义`[]🔰 手动切换`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇩🇪 德国节点`[]🗺️ 其他地区`[]🔰 手动切换`[]♻️ 自动选择

custom_proxy_group=🇭🇰 香港节点`select`(港|HK|hk|Hong Kong|HongKong|hongkong)
custom_proxy_group=♊ 香港故转`fallback`(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong))^((?!(深港|5倍)).)*$`http://www.gstatic.com/generate_204`180
custom_proxy_group=🇸🇬 狮城节点`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🪯 狮城故转`fallback`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(深港|5倍)).)*$`http://www.gstatic.com/generate_204`180  
custom_proxy_group=🇯🇵 日本节点`select`(日本|JP|Japan)
custom_proxy_group=🔯 日本故转`fallback`(?=.*(日本|东京|JP|Japan))^((?!(深港|5倍)).)*$`http://www.gstatic.com/generate_204`180
custom_proxy_group=🇺🇸 美国节点`select`(美|US|United States)
custom_proxy_group=☪️ 美国故转`fallback`(?=.*(美|US|United States))^((?!(深港|5倍)).)*$`http://www.gstatic.com/generate_204`180
custom_proxy_group=🇬🇧 英国节点`select`(英|GB|UK|United Kingdom)
custom_proxy_group=♈ 英国故转`fallback`(?=.*(英|GB|UK|United Kingdom))^((?!(深港|5倍)).)*$`http://www.gstatic.com/generate_204`180
custom_proxy_group=🇩🇪 德国节点`select`(德|DE|Germany)
custom_proxy_group=♉ 德国故转`fallback`(?=.*(德|DE|Germany))^((?!(深港|5倍)).)*$`http://www.gstatic.com/generate_204`180
custom_proxy_group=♒ ikuuu故转`fallback`(?i)^(?!.*(THANK|CDN|美|德)).*(免费|日本).*$`http://www.gstatic.com/generate_204`180
custom_proxy_group=🗺️ 其他地区`select`(^(?!.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|JP|Japan|新加坡|坡|狮城|SG|Singapore|美|US|United States|英|GB|UK|United Kingdom|德|DE|Germany)).*)




;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
